# Generated by Django 4.1.3 on 2022-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kgn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgn',
            name='summary',
            field=models.TextField(default='Cool'),
        ),
        migrations.AlterField(
            model_name='kgn',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kgn',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
