# Generated by Django 4.1.3 on 2022-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kgn', '0002_kgn_summary_alter_kgn_description_alter_kgn_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(default='Cool')),
            ],
        ),
    ]
