# Generated by Django 4.1.3 on 2022-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kgn', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('authored_books', models.TextField(default='Harry Potter')),
            ],
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
